In [26]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve


# 1 calculating determinant and cheching if it is not equal to 0
matrix_a = np.array([[32, -115, 38], [8, 13, -64], [24, 72, -12]], dtype="float")

bias_matrix = np.array([28, -65, 45], dtype="float")

determinant = np.linalg.det(matrix_a)

print(f"1.\nВизначник: {determinant}")
print(f"Визначник != 0: {determinant != 0}")


# 2 Cramer's method
def cramer(A, b):
    det_A = np.linalg.det(A)

    x = np.zeros(len(b))
    for i in range(len(b)):
        A_i = A.copy()
        A_i[:, i] = b

        det_A_i = np.linalg.det(A_i)
        x[i] = det_A_i / det_A

    return x


matrix_cramer = cramer(matrix_a, bias_matrix)
print(f"\n2.\nРозв'язок за допомогою методу Крамера: X = {matrix_cramer}")

# check solution
print("Перевірка розв'язку по співпадінню з bias_matrix:")
print(np.matmul(matrix_a, matrix_cramer))


# 3 inverse of the coefficient matrix with unknowns
print("\n3.\nРішення за допомогою оберненої матриці: ")

matrix_a_inv = np.linalg.inv(matrix_a)
matrix_inv = np.matmul(matrix_a_inv, bias_matrix)
print(f"X = {matrix_inv}")

# check solution
print(f"Перевірка властивості оберненої матриці: \n{np.matmul(matrix_a_inv, matrix_a)}")


# 4 gauss elimination method
"""Отримання комбінованої матриці L та U та перестановок рядків piv"""
matrix_lu, piv = lu_factor(matrix_a)
print(f"\n4.\nКомбінована матриця LU: \n{matrix_lu}")

matrix_l = np.tril(matrix_lu, k=-1) + np.eye(3)
matrix_u = np.triu(matrix_lu)

print(f"\nМатриця L: \n{matrix_l}")
print(f"\nМатриця U: \n{matrix_u}")


def pivot_to_permutation(piv):
    perm = np.arange(len(piv))
    for i in range(len(piv)):
        perm[i], perm[piv[i]] = perm[piv[i]], perm[i]
    return perm


p_indices = pivot_to_permutation(piv)
print(f"\nІндекси перестановок: {p_indices}")

# check if LU=PA
print("\n Перевірка умови LU = PA:")
lu_product = np.matmul(matrix_l, matrix_u)
print(lu_product[np.argsort(p_indices)])

# solve
matrix_gauss = lu_solve((matrix_lu, piv), bias_matrix)
print(f"\nРозв'язок за допомогою методу Гауса: X = {matrix_gauss}")

1.
Визначник: 318096.00000000023
Визначник != 0: True

2.
Розв'язок за допомогою методу Крамера: X = [1.08610608 0.47080127 1.24701977]
Перевірка розв'язку по співпадінню з bias_matrix:
[ 28. -65.  45.]

3.
Рішення за допомогою оберненої матриці: 
X = [1.08610608 0.47080127 1.24701977]
Перевірка властивості оберненої матриці: 
[[ 1.00000000e+00 -1.94289029e-16  1.80411242e-16]
 [ 0.00000000e+00  1.00000000e+00  2.77555756e-17]
 [ 0.00000000e+00  8.32667268e-17  1.00000000e+00]]

4.
Комбінована матриця LU: 
[[  32.         -115.           38.        ]
 [   0.75        158.25        -40.5       ]
 [   0.25          0.26382306  -62.81516588]]

Матриця L: 
[[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.26382306 1.        ]]

Матриця U: 
[[  32.         -115.           38.        ]
 [   0.          158.25        -40.5       ]
 [   0.            0.          -62.81516588]]

Індекси перестановок: [0 2 1]

 Перевірка умови LU = PA:
[[  32. -115.   38.]
 [